# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdb745f2b922a7df8fe959c7f2670604363089a99f7ab8c994efe1fd1dbae6f8019edb05266ef12dd946ce0047a120d25154deb00e41fd17e1d5adf2ee7fc0d0

test:
  secret_key_base: 623e7d73ae740057a7e713bb420950a6e7f4a0f2632574cc7d7a13dce214b325f40c210635be339ce46bfb1db99e2b1c4ceccf7dc67bd6fde4c1c8b463f7e1fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
